# Generated by Django 5.2.6 on 2025-09-24 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('senha', models.FloatField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='RegistroMed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicamento', models.CharField(max_length=100)),
                ('dosagem', models.FloatField()),
                ('data_inicio', models.DateField()),
                ('data_termino', models.DateField()),
                ('horario', models.IntegerField()),
                ('imagem', models.ImageField(upload_to='')),
            ],
        ),
    ]
