# Generated by Django 5.2.6 on 2025-09-24 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMed', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro',
            name='senha',
            field=models.CharField(max_length=128),
        ),
    ]
