# Generated by Django 5.2.6 on 2025-11-12 19:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMed', '0002_alter_registro_senha'),
    ]

    operations = [
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Idoso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('data_nascimento', models.DateField(blank=True, null=True)),
                ('observacoes', models.TextField(blank=True, default='')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('responsavel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='idosos', to='appMed.registro')),
            ],
        ),
        migrations.CreateModel(
            name='Medicamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('dosagem', models.CharField(max_length=80)),
                ('data_inicio', models.DateField()),
                ('data_termino', models.DateField(blank=True, null=True)),
                ('frequencia_tipo', models.CharField(choices=[('horarios_fixos', 'Horários fixos'), ('intervalo_horas', 'Intervalo em horas')], default='horarios_fixos', max_length=20)),
                ('intervalo_horas', models.PositiveIntegerField(blank=True, null=True)),
                ('dias_semana', models.CharField(blank=True, default='', max_length=50)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('idoso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicamentos', to='appMed.idoso')),
            ],
        ),
        migrations.CreateModel(
            name='Tomada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horario_previsto', models.DateTimeField()),
                ('tomado', models.BooleanField(default=False)),
                ('data_hora_tomada', models.DateTimeField(blank=True, null=True)),
                ('observacao', models.TextField(blank=True, default='')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tomadas_registradas', to='appMed.registro')),
                ('idoso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tomadas', to='appMed.idoso')),
                ('medicamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tomadas', to='appMed.medicamento')),
            ],
        ),
        migrations.DeleteModel(
            name='RegistroMed',
        ),
        migrations.AddField(
            model_name='horario',
            name='medicamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='appMed.medicamento'),
        ),
    ]
